from __future__ import annotations

from dataclasses import dataclass, field
from io import StringIO

from .ast import Binary, Comparison, Expr, Goto, Grouped, If, Input, Label, Let, Number, Print, Program, Unary, Variable, While
from .semantics import SemanticModel


@dataclass
class CEmitter:
    """AST -> C backend. No parsing or semantic analysis occurs here."""

    indent_width: int = 4
    _header: list[str] = field(default_factory=list, init=False)
    _body: list[str] = field(default_factory=list, init=False)
    _indent: int = field(default=1, init=False)

    def emit_program(self, program: Program, model: SemanticModel) -> str:
        self._header = ["#include <stdio.h>"]
        self._body = []
        self._indent = 1

        self._header.append("")
        self._header.append("/* Variables generated by semantic analysis. */")
        for name in sorted(model.symbols):
            self._header.append(f"float {name};")
        self._header.append("")

        self._body.append("int main(void) {")
        for stmt in program.statements:
            self._stmt(stmt)
        self._body.append("    return 0;")
        self._body.append("}")
        return "\n".join(self._header + self._body) + "\n"

    def _line(self, text: str) -> None:
        self._body.append(" " * (self._indent * self.indent_width) + text)

    def _stmt(self, stmt) -> None:
        if isinstance(stmt, Print):
            if stmt.is_string:
                text = str(stmt.value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
                self._line(f'printf("{text}\\n");')
            else:
                self._line(f"printf(\"%.2f\\n\", (float)({self._expr(stmt.value)}));")
        elif isinstance(stmt, Input):
            self._line(f'if (scanf("%f", &{stmt.name}) != 1) {{')
            self._indent += 1
            self._line(f"{stmt.name} = 0;")
            self._line('scanf("%*s");')
            self._indent -= 1
            self._line("}")
        elif isinstance(stmt, Let):
            self._line(f"{stmt.name} = {self._expr(stmt.value)};")
        elif isinstance(stmt, If):
            self._line(f"if ({self._expr(stmt.condition)}) {{")
            self._indent += 1
            for child in stmt.body:
                self._stmt(child)
            self._indent -= 1
            self._line("}")
        elif isinstance(stmt, While):
            self._line(f"while ({self._expr(stmt.condition)}) {{")
            self._indent += 1
            for child in stmt.body:
                self._stmt(child)
            self._indent -= 1
            self._line("}")
        elif isinstance(stmt, Label):
            # Labels need special indentation in C.
            self._body.append(f"{stmt.name}:")
        elif isinstance(stmt, Goto):
            self._line(f"goto {stmt.name};")

    def _expr(self, expr: Expr) -> str:
        if isinstance(expr, Number):
            return expr.value
        if isinstance(expr, Variable):
            return expr.name
        if isinstance(expr, Grouped):
            return self._expr(expr.value)
        if isinstance(expr, Unary):
            return f"({expr.operator}{self._expr(expr.operand)})"
        if isinstance(expr, Binary):
            return f"({self._expr(expr.left)} {expr.operator} {self._expr(expr.right)})"
        if isinstance(expr, Comparison):
            return f"({self._expr(expr.left)} {expr.operator} {self._expr(expr.right)})"
        raise TypeError(f"Unsupported expression node: {type(expr).__name__}")
